### ISSUE TITLE
Создание интерфейса для приложения!

### ISSUE THREAD

**Issue by alina-pylypenko** [alina-pylypenko/ScedulerForStudents#6]
№1 Продолжение оформления интерфейса.
№2 Формирование Календаря.
№3 Разработка ленты новостей.

**Comment by AljonaMaljuga** [comment]
№1 Продолжение оформления интерфейса - предворительный вариант
№2 Формирование Календаря - выполнено

**Comment by AljonaMaljuga** [comment]
№3 Разработка ленты новостей- предворительный вариант
